"""SQLAlchemy models for the Lens product catalogue.

=============================================================================
CRITICAL — faiss_index and id are NOT interchangeable.
=============================================================================
The search pipeline (ai/search_system.py:86) resolves FAISS hits positionally:

    distances, indices = index.search(q_emb, retrieve_n)
    row = df.iloc[idx]          # idx is a ROW POSITION, not a product id

FAISS knows nothing about product ids — it returns the ordinal position of a
vector inside product_index.faiss. That position only means something because
the metadata was built in the same order as the vectors (both 44419 long).

`faiss_index` preserves that ordering in the database: faiss_index == the row's
position in ai/models/product_metadata.json, 0..44418. `id` is the dataset's
own product id (1163..60000, sparse and unordered) used for the API response
and image URLs.

Product 0 has id=15970. Confusing the two returns plausible-looking but wrong
products for every query, with the AI pipeline completely untouched — which is
why faiss_index is NOT NULL + UNIQUE + indexed, and why the seed script asserts
the ordering rather than trusting it.
=============================================================================

Column nullability below was derived by profiling the 44419 rows of
product_metadata.json, not assumed. Null counts at seed time:
    productDisplayName 7 | baseColour 15 | season 21 | year 1 | usage 317
    id, masterCategory, subCategory, articleType, gender: no nulls
"""
from __future__ import annotations

from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    Boolean,
    Computed,
    DateTime,
    Index,
    Integer,
    Numeric,
    SmallInteger,
    String,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class User(Base):
    """An authenticated account (Phase 1 auth).

    Unlike Product.id (real, sparse dataset ids), user ids are surrogate keys
    generated by the database. email is the login identifier and is unique;
    password_hash holds a bcrypt hash — never a plaintext password.
    """

    __tablename__ = "users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    # Login identifier. Stored lowercased by the register endpoint; unique +
    # indexed so lookups on login are fast and duplicates are impossible.
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    # bcrypt hash (60 chars for $2b$); column is oversized to tolerate future
    # algorithm changes. NEVER stores plaintext.
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    is_admin: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=text("false")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<User id={self.id} email={self.email!r} is_admin={self.is_admin}>"


class Product(Base):
    """One row of the fashion product catalogue.

    Attribute names are snake_case; the search code consumes the original
    camelCase dataset names, so server.py maps between them when it builds the
    DataFrame it hands to ai.search_system.build_search.
    """

    __tablename__ = "products"

    # Dataset product id. Real, sparse ids from the source data — never
    # generated, so no autoincrement. Used for /images/{id}.jpg.
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)

    # Row position in product_index.faiss / product_metadata.json (0..44418).
    # The alignment guarantee the entire search depends on. See module docstring.
    faiss_index: Mapped[int] = mapped_column(
        Integer, nullable=False, unique=True, index=True
    )

    # --- Fields returned by the search API ---------------------------------
    # 7 nulls in the source data.
    product_display_name: Mapped[str | None] = mapped_column(String(255))
    # API "category". No nulls.
    master_category: Mapped[str] = mapped_column(String(64), nullable=False)
    # NOTE: the API's "subCategory" field is fed from article_type, not this
    # column — see server.py. Stored for completeness/filtering. No nulls.
    sub_category: Mapped[str] = mapped_column(String(64), nullable=False)
    # Re-ranker category boost + query-parser vocabulary. No nulls.
    article_type: Mapped[str] = mapped_column(String(64), nullable=False)
    # Re-ranker colour boost + vocabulary. 15 nulls.
    base_colour: Mapped[str | None] = mapped_column(String(64))
    # Re-ranker gender boost. No nulls.
    gender: Mapped[str] = mapped_column(String(32), nullable=False)

    # --- Catalogue fields, not currently returned by search ----------------
    season: Mapped[str | None] = mapped_column(String(32))  # 21 nulls
    year: Mapped[int | None] = mapped_column(SmallInteger)  # 1 null; 2007-2019
    usage: Mapped[str | None] = mapped_column(String(32))  # 317 nulls

    # --- Commerce fields (Phase 2) -----------------------------------------
    # The source fashion dataset carries no price or stock. These are backfilled
    # deterministically from id (migration f_add_commerce) so values are stable
    # and reproducible — real enough for catalog sort/filter and cart totals.
    price: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    in_stock: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true")
    )

    # --- Full-text search (Phase 2 step 3) ---------------------------------
    # STORED generated column over name + article type + colour, kept in sync
    # automatically. Must use the immutable 'english'::regconfig form (a plain
    # 'english' text arg is only STABLE and a generated column rejects it).
    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed(
            "to_tsvector('english'::regconfig, "
            "coalesce(product_display_name, '') || ' ' || "
            "coalesce(article_type, '') || ' ' || "
            "coalesce(base_colour, ''))",
            persisted=True,
        ),
        nullable=True,
    )

    # Composite index supporting the faceted filtering the storefront will do
    # (category + colour + gender are exactly the re-ranker's boost fields).
    __table_args__ = (
        Index("ix_products_facets", "article_type", "base_colour", "gender"),
        # Price is a primary sort/filter axis on the catalog page.
        Index("ix_products_price", "price"),
        # GIN over the tsvector for full-text (@@) queries.
        Index("ix_products_search_vector", "search_vector", postgresql_using="gin"),
        # Trigram GIN on the name for fuzzy/typo (% operator) matching.
        Index(
            "ix_products_name_trgm",
            "product_display_name",
            postgresql_using="gin",
            postgresql_ops={"product_display_name": "gin_trgm_ops"},
        ),
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return (
            f"<Product id={self.id} faiss_index={self.faiss_index} "
            f"name={self.product_display_name!r}>"
        )
