"""SQLAlchemy models for the Lens product catalogue.

=============================================================================
CRITICAL — faiss_index and id are NOT interchangeable.
=============================================================================
The search pipeline (ai/search_system.py:86) resolves FAISS hits positionally:

    distances, indices = index.search(q_emb, retrieve_n)
    row = df.iloc[idx]          # idx is a ROW POSITION, not a product id

FAISS knows nothing about product ids — it returns the ordinal position of a
vector inside product_index.faiss. That position only means something because
the metadata was built in the same order as the vectors (both 44419 long).

`faiss_index` preserves that ordering in the database: faiss_index == the row's
position in ai/models/product_metadata.json, 0..44418. `id` is the dataset's
own product id (1163..60000, sparse and unordered) used for the API response
and image URLs.

Product 0 has id=15970. Confusing the two returns plausible-looking but wrong
products for every query, with the AI pipeline completely untouched — which is
why faiss_index is NOT NULL + UNIQUE + indexed, and why the seed script asserts
the ordering rather than trusting it.
=============================================================================

Column nullability below was derived by profiling the 44419 rows of
product_metadata.json, not assumed. Null counts at seed time:
    productDisplayName 7 | baseColour 15 | season 21 | year 1 | usage 317
    id, masterCategory, subCategory, articleType, gender: no nulls
"""
from __future__ import annotations

from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    SmallInteger,
    String,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class User(Base):
    """An authenticated account (Phase 1 auth).

    Unlike Product.id (real, sparse dataset ids), user ids are surrogate keys
    generated by the database. email is the login identifier and is unique;
    password_hash holds a bcrypt hash — never a plaintext password.
    """

    __tablename__ = "users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    # Login identifier. Stored lowercased by the register endpoint; unique +
    # indexed so lookups on login are fast and duplicates are impossible.
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    # bcrypt hash (60 chars for $2b$); column is oversized to tolerate future
    # algorithm changes. NEVER stores plaintext.
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    is_admin: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=text("false")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<User id={self.id} email={self.email!r} is_admin={self.is_admin}>"


class Product(Base):
    """One row of the fashion product catalogue.

    Attribute names are snake_case; the search code consumes the original
    camelCase dataset names, so server.py maps between them when it builds the
    DataFrame it hands to ai.search_system.build_search.
    """

    __tablename__ = "products"

    # Dataset product id. Real, sparse ids from the source data — never
    # generated, so no autoincrement. Used for /images/{id}.jpg.
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)

    # Row position in product_index.faiss / product_metadata.json (0..44418).
    # The alignment guarantee the entire search depends on. See module docstring.
    faiss_index: Mapped[int] = mapped_column(
        Integer, nullable=False, unique=True, index=True
    )

    # --- Fields returned by the search API ---------------------------------
    # 7 nulls in the source data.
    product_display_name: Mapped[str | None] = mapped_column(String(255))
    # API "category". No nulls.
    master_category: Mapped[str] = mapped_column(String(64), nullable=False)
    # NOTE: the API's "subCategory" field is fed from article_type, not this
    # column — see server.py. Stored for completeness/filtering. No nulls.
    sub_category: Mapped[str] = mapped_column(String(64), nullable=False)
    # Re-ranker category boost + query-parser vocabulary. No nulls.
    article_type: Mapped[str] = mapped_column(String(64), nullable=False)
    # Re-ranker colour boost + vocabulary. 15 nulls.
    base_colour: Mapped[str | None] = mapped_column(String(64))
    # Re-ranker gender boost. No nulls.
    gender: Mapped[str] = mapped_column(String(32), nullable=False)

    # --- Catalogue fields, not currently returned by search ----------------
    season: Mapped[str | None] = mapped_column(String(32))  # 21 nulls
    year: Mapped[int | None] = mapped_column(SmallInteger)  # 1 null; 2007-2019
    usage: Mapped[str | None] = mapped_column(String(32))  # 317 nulls

    # --- Commerce fields (Phase 2) -----------------------------------------
    # The source fashion dataset carries no price or stock. These are backfilled
    # deterministically from id (migration f_add_commerce) so values are stable
    # and reproducible — real enough for catalog sort/filter and cart totals.
    price: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    in_stock: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true")
    )
    # Units on hand (Phase 3). Backfilled deterministically from id, consistent
    # with in_stock (0 when out of stock). Checkout decrements it and keeps
    # in_stock = (stock_quantity > 0) in sync.
    stock_quantity: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Soft delete (Phase 4). Admin "delete" clears this flag; the ROW STAYS.
    #
    # A hard DELETE is forbidden and always will be: faiss_index must remain a
    # contiguous 0..n-1 sequence (see the module docstring), and server.py
    # asserts exactly that at startup. Removing a row shifts every later
    # position, so the next boot either raises or — worse, if the assert were
    # ever removed — silently returns the wrong product for every image query.
    #
    # Inactive products are filtered out of catalog and search RESULTS, but are
    # deliberately still loaded into the metadata DataFrame, because that
    # frame's row order IS the FAISS alignment.
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true")
    )

    # --- Full-text search (Phase 2 step 3) ---------------------------------
    # STORED generated column over name + article type + colour, kept in sync
    # automatically. Must use the immutable 'english'::regconfig form (a plain
    # 'english' text arg is only STABLE and a generated column rejects it).
    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed(
            "to_tsvector('english'::regconfig, "
            "coalesce(product_display_name, '') || ' ' || "
            "coalesce(article_type, '') || ' ' || "
            "coalesce(base_colour, ''))",
            persisted=True,
        ),
        nullable=True,
    )

    # Composite index supporting the faceted filtering the storefront will do
    # (category + colour + gender are exactly the re-ranker's boost fields).
    __table_args__ = (
        Index("ix_products_facets", "article_type", "base_colour", "gender"),
        # Price is a primary sort/filter axis on the catalog page.
        Index("ix_products_price", "price"),
        # GIN over the tsvector for full-text (@@) queries.
        Index("ix_products_search_vector", "search_vector", postgresql_using="gin"),
        # Trigram GIN on the name for fuzzy/typo (% operator) matching.
        Index(
            "ix_products_name_trgm",
            "product_display_name",
            postgresql_using="gin",
            postgresql_ops={"product_display_name": "gin_trgm_ops"},
        ),
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return (
            f"<Product id={self.id} faiss_index={self.faiss_index} "
            f"name={self.product_display_name!r}>"
        )


class CartItem(Base):
    """One product line in a user's cart (Phase 2).

    At most one row per (user, product) — quantity is bumped instead of adding a
    second row. Both foreign keys cascade on delete, so removing a user (or a
    product) cleans up their cart lines automatically.
    """

    __tablename__ = "cart_items"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    product_id: Mapped[int] = mapped_column(
        ForeignKey("products.id", ondelete="CASCADE"), nullable=False
    )
    quantity: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        UniqueConstraint("user_id", "product_id", name="uq_cart_items_user_product"),
        CheckConstraint("quantity >= 1", name="ck_cart_items_quantity_positive"),
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return (
            f"<CartItem user={self.user_id} product={self.product_id} "
            f"qty={self.quantity}>"
        )


class WishlistItem(Base):
    """A product a user has saved (Phase 2). One row per (user, product)."""

    __tablename__ = "wishlist_items"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    product_id: Mapped[int] = mapped_column(
        ForeignKey("products.id", ondelete="CASCADE"), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        UniqueConstraint("user_id", "product_id", name="uq_wishlist_items_user_product"),
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<WishlistItem user={self.user_id} product={self.product_id}>"


class RecentlyViewed(Base):
    """A product a user recently opened (Phase 2).

    One row per (user, product); re-viewing bumps viewed_at (upsert) instead of
    inserting a duplicate, so the list stays de-duplicated and most-recent-first.
    """

    __tablename__ = "recently_viewed"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    product_id: Mapped[int] = mapped_column(
        ForeignKey("products.id", ondelete="CASCADE"), nullable=False
    )
    viewed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        UniqueConstraint("user_id", "product_id", name="uq_recently_viewed_user_product"),
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<RecentlyViewed user={self.user_id} product={self.product_id}>"


class Address(Base):
    """A saved shipping address (Phase 3). Orders snapshot the address at
    checkout, so editing/deleting one later never mutates a placed order."""

    __tablename__ = "addresses"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    full_name: Mapped[str] = mapped_column(String(255), nullable=False)
    phone: Mapped[str] = mapped_column(String(32), nullable=False)
    line1: Mapped[str] = mapped_column(String(255), nullable=False)
    line2: Mapped[str | None] = mapped_column(String(255))
    city: Mapped[str] = mapped_column(String(128), nullable=False)
    state: Mapped[str] = mapped_column(String(128), nullable=False)
    postal_code: Mapped[str] = mapped_column(String(32), nullable=False)
    country: Mapped[str] = mapped_column(String(64), nullable=False, server_default=text("'US'"))
    is_default: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=text("false")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


# The complete set of order statuses (Phase 4). Kept here so the DB CHECK
# constraint below and the transition rules in orders.py are driven by one
# definition and cannot drift apart.
#
#   pending    created, not yet successfully paid
#   paid       payment succeeded, not yet dispatched
#   shipped    dispatched to the customer
#   delivered  received by the customer
#   cancelled  ended before dispatch (customer or admin)
#   returned   a delivered order the customer sent back
#   refunded   money returned; terminal, reachable from cancelled/returned
ORDER_STATUSES = (
    "pending",
    "paid",
    "shipped",
    "delivered",
    "cancelled",
    "returned",
    "refunded",
)


class Order(Base):
    """An order created from a user's cart at checkout (Phase 3).

    The shipping address is stored as a JSONB snapshot and each line's price is
    snapshotted in order_items, so a placed order is immutable regardless of
    later product/address/price changes.

    status moves through ORDER_STATUSES above; every change is appended to
    order_status_history (Phase 4) so the customer-facing timeline and any
    audit question can be answered from the record rather than inferred.
    """

    __tablename__ = "orders"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    # Human-facing reference (e.g. LENS-XXXXXXXXXX); not the sequential id.
    order_number: Mapped[str] = mapped_column(String(32), unique=True, nullable=False, index=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    status: Mapped[str] = mapped_column(String(32), nullable=False, server_default=text("'pending'"))
    shipping_address: Mapped[dict] = mapped_column(JSONB, nullable=False)

    # Money breakdown; total = subtotal - discount + tax + shipping.
    subtotal: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    discount: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False, server_default=text("0"))
    tax: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    shipping: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    total: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    coupon_code: Mapped[str | None] = mapped_column(String(32))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # Lifecycle timestamps (Phase 4). Each is set once, when the order first
    # enters that state; status alone cannot answer "when did it ship?" and
    # these also feed the fulfilment figures in the analytics endpoints.
    shipped_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    delivered_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    cancelled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    cancel_reason: Mapped[str | None] = mapped_column(String(255))
    # A return is *requested* by the customer and then approved by an admin,
    # so the request time is recorded separately from the status change.
    return_requested_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    return_reason: Mapped[str | None] = mapped_column(String(255))

    items: Mapped[list["OrderItem"]] = relationship(
        back_populates="order", cascade="all, delete-orphan", order_by="OrderItem.id"
    )
    payments: Mapped[list["Payment"]] = relationship(
        back_populates="order", cascade="all, delete-orphan", order_by="Payment.id"
    )
    status_history: Mapped[list["OrderStatusHistory"]] = relationship(
        back_populates="order", cascade="all, delete-orphan", order_by="OrderStatusHistory.id"
    )

    __table_args__ = (
        CheckConstraint(
            "status IN " + str(ORDER_STATUSES),
            name="ck_orders_status_valid",
        ),
    )


class OrderItem(Base):
    """One line of an order. product_name/unit_price are snapshots taken at
    checkout so the line is stable even if the product later changes or is
    removed (product_id goes NULL on delete)."""

    __tablename__ = "order_items"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    order_id: Mapped[int] = mapped_column(
        ForeignKey("orders.id", ondelete="CASCADE"), nullable=False, index=True
    )
    product_id: Mapped[int | None] = mapped_column(
        ForeignKey("products.id", ondelete="SET NULL")
    )
    product_name: Mapped[str] = mapped_column(String(255), nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    quantity: Mapped[int] = mapped_column(Integer, nullable=False)
    line_total: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)

    order: Mapped["Order"] = relationship(back_populates="items")


class Payment(Base):
    """A simulated payment attempt against an order (Phase 3). No real funds
    move and no full card number is ever stored — `detail` holds only masked
    data (e.g. card last-4 or UPI handle)."""

    __tablename__ = "payments"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    order_id: Mapped[int] = mapped_column(
        ForeignKey("orders.id", ondelete="CASCADE"), nullable=False, index=True
    )
    method: Mapped[str] = mapped_column(String(16), nullable=False)  # upi | card | wallet
    # success | failed | refunded — a successful payment becomes 'refunded'
    # in place rather than gaining a second row, so at most one payment per
    # order ever counts as money received (see orders.py:_latest_payment_status).
    status: Mapped[str] = mapped_column(String(16), nullable=False)
    amount: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    transaction_ref: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    detail: Mapped[dict | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    # Refund bookkeeping (Phase 4). Simulated like the original charge: no
    # funds move, but the reference makes the refund traceable in the UI.
    refunded_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    refund_ref: Mapped[str | None] = mapped_column(String(64))

    order: Mapped["Order"] = relationship(back_populates="payments")


class OrderStatusHistory(Base):
    """One recorded status change for an order (Phase 4).

    Append-only: rows are never updated or deleted, so the sequence is the
    order's audit trail and the source for the customer-facing timeline.
    from_status is NULL only for the row recording the order's creation.
    changed_by_user_id is the admin who acted, or NULL when the change came
    from the customer or from the system (e.g. payment success).
    """

    __tablename__ = "order_status_history"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    order_id: Mapped[int] = mapped_column(
        ForeignKey("orders.id", ondelete="CASCADE"), nullable=False, index=True
    )
    from_status: Mapped[str | None] = mapped_column(String(32))
    to_status: Mapped[str] = mapped_column(String(32), nullable=False)
    note: Mapped[str | None] = mapped_column(String(255))
    # SET NULL, not CASCADE: deleting an admin must not erase the history of
    # orders they touched.
    changed_by_user_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    order: Mapped["Order"] = relationship(back_populates="status_history")

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return (
            f"<OrderStatusHistory order={self.order_id} "
            f"{self.from_status} -> {self.to_status}>"
        )
