"""phase4 stock_adjustments ledger

Append-only audit of every change to products.stock_quantity.

Deliberately NOT backfilled. Writing an opening-balance row for all 44,419
seeded products would add rows that record nothing anyone did — the seeded
quantities came from a deterministic hash in migration 0d9d0a24955c, not from a
stock movement. The ledger therefore starts empty and explains changes from this
point on; the opening balance for any product is quantity_before on its earliest
row (or its current stock_quantity if it has no rows yet).

Revision ID: 2e3bb2bfc843
Revises: 6fe0d60423dc
Create Date: 2026-07-31 02:26:06.861111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3bb2bfc843'
down_revision: Union[str, Sequence[str], None] = '6fe0d60423dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('delta <> 0', name='ck_stock_adjustments_delta_nonzero'),
    sa.CheckConstraint('quantity_after >= 0', name='ck_stock_adjustments_after_nonneg'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_adjustments_order_id'), 'stock_adjustments', ['order_id'], unique=False)
    # Covers lookups by product on its own as well as the product+time reads the
    # history endpoint does, so no separate index on product_id.
    op.create_index('ix_stock_adjustments_product_created', 'stock_adjustments', ['product_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_adjustments_product_created', table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_order_id'), table_name='stock_adjustments')
    op.drop_table('stock_adjustments')
    # ### end Alembic commands ###
