"""create products table

Revision ID: 4d4c7949cf49
Revises: 
Create Date: 2026-07-23 21:50:57.721367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4c7949cf49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('faiss_index', sa.Integer(), nullable=False),
    sa.Column('product_display_name', sa.String(length=255), nullable=True),
    sa.Column('master_category', sa.String(length=64), nullable=False),
    sa.Column('sub_category', sa.String(length=64), nullable=False),
    sa.Column('article_type', sa.String(length=64), nullable=False),
    sa.Column('base_colour', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('season', sa.String(length=32), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('usage', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_facets', 'products', ['article_type', 'base_colour', 'gender'], unique=False)
    op.create_index(op.f('ix_products_faiss_index'), 'products', ['faiss_index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_faiss_index'), table_name='products')
    op.drop_index('ix_products_facets', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
