"""phase4 order lifecycle: status history, lifecycle timestamps, refunds

Revision ID: 9366ebb80d80
Revises: 0d9d0a24955c
Create Date: 2026-07-29 16:24:22.510312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9366ebb80d80'
down_revision: Union[str, Sequence[str], None] = '0d9d0a24955c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('cancel_reason', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('return_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('return_reason', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('refund_ref', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###

    # --- hand-written below (autogenerate does not detect CHECK constraints) ---

    # Restrict status to models.ORDER_STATUSES. Existing rows are only
    # 'pending'/'paid', both members, so this validates without a backfill.
    op.create_check_constraint(
        "ck_orders_status_valid",
        "orders",
        "status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled', "
        "'returned', 'refunded')",
    )

    # Seed order_status_history for orders that predate it, so the timeline in
    # the UI is not blank for them. The real sequence is not recoverable, but
    # for the only statuses that exist so far it is reconstructable exactly:
    # every order began as 'pending' at orders.created_at, and a 'paid' order
    # got there when its successful payment landed.
    op.execute(
        "INSERT INTO order_status_history "
        "  (order_id, from_status, to_status, note, created_at) "
        "SELECT id, NULL, 'pending', 'backfilled by migration', created_at "
        "FROM orders"
    )
    op.execute(
        "INSERT INTO order_status_history "
        "  (order_id, from_status, to_status, note, created_at) "
        "SELECT o.id, 'pending', o.status, 'backfilled by migration', "
        "       COALESCE(("
        "         SELECT MIN(p.created_at) FROM payments p "
        "         WHERE p.order_id = o.id AND p.status = 'success'"
        "       ), o.created_at) "
        "FROM orders o WHERE o.status <> 'pending'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Hand-written: mirrors the CHECK constraint added in upgrade(). The
    # backfilled history rows need no explicit cleanup — dropping the table
    # below takes them with it.
    op.drop_constraint("ck_orders_status_valid", "orders", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'refund_ref')
    op.drop_column('payments', 'refunded_at')
    op.drop_column('orders', 'return_reason')
    op.drop_column('orders', 'return_requested_at')
    op.drop_column('orders', 'cancel_reason')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'shipped_at')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    # ### end Alembic commands ###
